// Generated by svd_parser.rb. Dont't edit please.
#ifndef IGB_GD32_BASE_MCU_GD32F350_H
#define IGB_GD32_BASE_MCU_GD32F350_H

#include <igb_gd32/base/mcu/device/gd32f350.hpp>

#endif /* IGB_GD32_BASE_MCU_GD32F350_H */
