// Generated by svd_parser.rb. Dont't edit please.
#ifndef IGB_STM32_BASE_MCU_STM32G031XX_H
#define IGB_STM32_BASE_MCU_STM32G031XX_H

#include <igb_stm32/base/mcu/device/stm32g031xx.hpp>

#endif /* IGB_STM32_BASE_MCU_STM32G031XX_H */
