// Generated by svd_parser.rb. Dont't edit please.
#ifndef IGB_STM32_BASE_MCU_STM32G431XX_H
#define IGB_STM32_BASE_MCU_STM32G431XX_H

#include <igb_stm32/base/mcu/device/stm32g431xx.hpp>

#endif /* IGB_STM32_BASE_MCU_STM32G431XX_H */
