// Generated by svd_parser.rb. Dont't edit please.
#ifndef IGB_STM32_BASE_MCU_STM32H750XX_H
#define IGB_STM32_BASE_MCU_STM32H750XX_H

#include <igb_stm32/base/mcu/device/stm32h750xx.hpp>

#endif /* IGB_STM32_BASE_MCU_STM32H750XX_H */
