// Generated by svd_parser.rb. Dont't edit please.
#ifndef IGB_STM32_BASE_MCU_STM32F303X8_H
#define IGB_STM32_BASE_MCU_STM32F303X8_H

#include <igb_stm32/base/mcu/device/stm32f303x8.hpp>

#endif /* IGB_STM32_BASE_MCU_STM32F303X8_H */
