// Generated by svd_parser.rb. Dont't edit please.
#ifndef IGB_STM32_BASE_MCU_DEVICE_STM32F446XX_H
#define IGB_STM32_BASE_MCU_DEVICE_STM32F446XX_H

#include <igb_stm32/base.hpp>
#include <array>
#include <optional>

#define STM32_PERIPHGRP_DCMI_EXISTS 1
#define STM32_PERIPH_DCMI_EXISTS 1
#define STM32_PERIPHGRP_FSMC_EXISTS 1
#define STM32_PERIPH_FMC_EXISTS 1
#define STM32_PERIPHGRP_DBG_EXISTS 1
#define STM32_PERIPH_DBG_EXISTS 1
#define STM32_PERIPHGRP_DMA_EXISTS 1
#define STM32_PERIPH_DMA2_EXISTS 1
#define STM32_PERIPH_DMA1_EXISTS 1
#define STM32_PERIPHGRP_RCC_EXISTS 1
#define STM32_PERIPH_RCC_EXISTS 1
#define STM32_PERIPHGRP_GPIO_EXISTS 1
#define STM32_PERIPH_GPIOH_EXISTS 1
#define STM32_PERIPH_GPIOG_EXISTS 1
#define STM32_PERIPH_GPIOF_EXISTS 1
#define STM32_PERIPH_GPIOE_EXISTS 1
#define STM32_PERIPH_GPIOD_EXISTS 1
#define STM32_PERIPH_GPIOC_EXISTS 1
#define STM32_PERIPH_GPIOB_EXISTS 1
#define STM32_PERIPH_GPIOA_EXISTS 1
#define STM32_PERIPHGRP_SYSCFG_EXISTS 1
#define STM32_PERIPH_SYSCFG_EXISTS 1
#define STM32_PERIPHGRP_SPI_EXISTS 1
#define STM32_PERIPH_SPI1_EXISTS 1
#define STM32_PERIPH_SPI2_EXISTS 1
#define STM32_PERIPH_SPI3_EXISTS 1
#define STM32_PERIPH_SPI4_EXISTS 1
#define STM32_PERIPHGRP_ADC_EXISTS 1
#define STM32_PERIPH_ADC1_EXISTS 1
#define STM32_PERIPH_ADC2_EXISTS 1
#define STM32_PERIPH_ADC3_EXISTS 1
#define STM32_PERIPH_C_ADC_EXISTS 1
#define STM32_PERIPHGRP_USART_EXISTS 1
#define STM32_PERIPH_USART6_EXISTS 1
#define STM32_PERIPH_USART1_EXISTS 1
#define STM32_PERIPH_USART2_EXISTS 1
#define STM32_PERIPH_USART3_EXISTS 1
#define STM32_PERIPH_UART4_EXISTS 1
#define STM32_PERIPH_UART5_EXISTS 1
#define STM32_PERIPHGRP_DAC_EXISTS 1
#define STM32_PERIPH_DAC1_EXISTS 1
#define STM32_PERIPHGRP_I2C_EXISTS 1
#define STM32_PERIPH_I2C3_EXISTS 1
#define STM32_PERIPH_I2C2_EXISTS 1
#define STM32_PERIPH_I2C1_EXISTS 1
#define STM32_PERIPHGRP_IWDG_EXISTS 1
#define STM32_PERIPH_IWDG_EXISTS 1
#define STM32_PERIPHGRP_WWDG_EXISTS 1
#define STM32_PERIPH_WWDG_EXISTS 1
#define STM32_PERIPHGRP_RTC_EXISTS 1
#define STM32_PERIPH_RTC_EXISTS 1
#define STM32_PERIPHGRP_TIM_EXISTS 1
#define STM32_PERIPH_TIM1_EXISTS 1
#define STM32_PERIPH_TIM8_EXISTS 1
#define STM32_PERIPH_TIM2_EXISTS 1
#define STM32_PERIPH_TIM3_EXISTS 1
#define STM32_PERIPH_TIM4_EXISTS 1
#define STM32_PERIPH_TIM5_EXISTS 1
#define STM32_PERIPH_TIM9_EXISTS 1
#define STM32_PERIPH_TIM12_EXISTS 1
#define STM32_PERIPH_TIM10_EXISTS 1
#define STM32_PERIPH_TIM13_EXISTS 1
#define STM32_PERIPH_TIM14_EXISTS 1
#define STM32_PERIPH_TIM11_EXISTS 1
#define STM32_PERIPH_TIM6_EXISTS 1
#define STM32_PERIPH_TIM7_EXISTS 1
#define STM32_PERIPHGRP_CRC_EXISTS 1
#define STM32_PERIPH_CRC_EXISTS 1
#define STM32_PERIPHGRP_USB_OTG_FS_EXISTS 1
#define STM32_PERIPH_OTG_FS_GLOBAL_EXISTS 1
#define STM32_PERIPH_OTG_FS_HOST_EXISTS 1
#define STM32_PERIPH_OTG_FS_DEVICE_EXISTS 1
#define STM32_PERIPH_OTG_FS_PWRCLK_EXISTS 1
#define STM32_PERIPHGRP_CAN_EXISTS 1
#define STM32_PERIPH_CAN1_EXISTS 1
#define STM32_PERIPH_CAN2_EXISTS 1
#define STM32_PERIPHGRP_NVIC_EXISTS 1
#define STM32_PERIPH_NVIC_EXISTS 1
#define STM32_PERIPH_NVIC_STIR_EXISTS 1
#define STM32_PERIPHGRP_FLASH_EXISTS 1
#define STM32_PERIPH_FLASH_EXISTS 1
#define STM32_PERIPHGRP_EXTI_EXISTS 1
#define STM32_PERIPH_EXTI_EXISTS 1
#define STM32_PERIPHGRP_USB_OTG_HS_EXISTS 1
#define STM32_PERIPH_OTG_HS_GLOBAL_EXISTS 1
#define STM32_PERIPH_OTG_HS_HOST_EXISTS 1
#define STM32_PERIPH_OTG_HS_DEVICE_EXISTS 1
#define STM32_PERIPH_OTG_HS_PWRCLK_EXISTS 1
#define STM32_PERIPHGRP_SAI_EXISTS 1
#define STM32_PERIPH_SAI1_EXISTS 1
#define STM32_PERIPH_SAI2_EXISTS 1
#define STM32_PERIPHGRP_PWR_EXISTS 1
#define STM32_PERIPH_PWR_EXISTS 1
#define STM32_PERIPHGRP_QUADSPI_EXISTS 1
#define STM32_PERIPH_QUADSPI_EXISTS 1
#define STM32_PERIPHGRP_SPDIF_RX_EXISTS 1
#define STM32_PERIPH_SPDIF_RX_EXISTS 1
#define STM32_PERIPHGRP_SDMMC_EXISTS 1
#define STM32_PERIPH_SDMMC_EXISTS 1
#define STM32_PERIPHGRP_HDMI_CEC_EXISTS 1
#define STM32_PERIPH_HDMI_CEC_EXISTS 1
#define STM32_PERIPHGRP_FPU_EXISTS 1
#define STM32_PERIPH_FPU_EXISTS 1
#define STM32_PERIPH_FPU_CPACR_EXISTS 1
#define STM32_PERIPHGRP_MPU_EXISTS 1
#define STM32_PERIPH_MPU_EXISTS 1
#define STM32_PERIPHGRP_STK_EXISTS 1
#define STM32_PERIPH_STK_EXISTS 1
#define STM32_PERIPHGRP_SCB_EXISTS 1
#define STM32_PERIPH_SCB_EXISTS 1
#define STM32_PERIPH_SCB_ACTRL_EXISTS 1

namespace igb {
namespace stm32 {

enum class PeriphGroupType : uint16_t {
  rcc = 0,
  gpio,
  spi,
  adc,
  usart,
  dac,
  i2c,
  tim,
};

enum class PeriphType : uint16_t {
  rcc = 0,
  gpioa,
  gpiob,
  gpioc,
  gpiod,
  gpioe,
  gpiof,
  gpiog,
  gpioh,
  spi1,
  spi2,
  spi3,
  spi4,
  adc1,
  adc2,
  adc3,
  usart1,
  usart2,
  usart3,
  uart4,
  uart5,
  usart6,
  dac1,
  i2c1,
  i2c2,
  i2c3,
  tim1,
  tim2,
  tim3,
  tim4,
  tim5,
  tim6,
  tim7,
  tim8,
  tim9,
  tim10,
  tim11,
  tim12,
  tim13,
  tim14,
};

enum class GpioType : uint8_t {
  gpioa = 0,
  gpiob,
  gpioc,
  gpiod,
  gpioe,
  gpiof,
  gpiog,
  gpioh,
};
enum class SpiType : uint8_t {
  spi1 = 0,
  spi2,
  spi3,
  spi4,
};
enum class AdcType : uint8_t {
  adc1 = 0,
  adc2,
  adc3,
};
enum class UsartType : uint8_t {
  usart1 = 0,
  usart2,
  usart3,
  uart4,
  uart5,
  usart6,
};
enum class DacType : uint8_t {
  dac1 = 0,
};
enum class I2cType : uint8_t {
  i2c1 = 0,
  i2c2,
  i2c3,
};
enum class TimType : uint8_t {
  tim1 = 0,
  tim2,
  tim3,
  tim4,
  tim5,
  tim6,
  tim7,
  tim8,
  tim9,
  tim10,
  tim11,
  tim12,
  tim13,
  tim14,
};

enum class GpioPinType : uint8_t {
  pa0 = (0 << 4) | 0,
  pa1 = (0 << 4) | 1,
  pa2 = (0 << 4) | 2,
  pa3 = (0 << 4) | 3,
  pa4 = (0 << 4) | 4,
  pa5 = (0 << 4) | 5,
  pa6 = (0 << 4) | 6,
  pa7 = (0 << 4) | 7,
  pa8 = (0 << 4) | 8,
  pa9 = (0 << 4) | 9,
  pa10 = (0 << 4) | 10,
  pa11 = (0 << 4) | 11,
  pa12 = (0 << 4) | 12,
  pa13 = (0 << 4) | 13,
  pa14 = (0 << 4) | 14,
  pa15 = (0 << 4) | 15,
  pb0 = (1 << 4) | 0,
  pb1 = (1 << 4) | 1,
  pb2 = (1 << 4) | 2,
  pb3 = (1 << 4) | 3,
  pb4 = (1 << 4) | 4,
  pb5 = (1 << 4) | 5,
  pb6 = (1 << 4) | 6,
  pb7 = (1 << 4) | 7,
  pb8 = (1 << 4) | 8,
  pb9 = (1 << 4) | 9,
  pb10 = (1 << 4) | 10,
  pb11 = (1 << 4) | 11,
  pb12 = (1 << 4) | 12,
  pb13 = (1 << 4) | 13,
  pb14 = (1 << 4) | 14,
  pb15 = (1 << 4) | 15,
  pc0 = (2 << 4) | 0,
  pc1 = (2 << 4) | 1,
  pc2 = (2 << 4) | 2,
  pc3 = (2 << 4) | 3,
  pc4 = (2 << 4) | 4,
  pc5 = (2 << 4) | 5,
  pc6 = (2 << 4) | 6,
  pc7 = (2 << 4) | 7,
  pc8 = (2 << 4) | 8,
  pc9 = (2 << 4) | 9,
  pc10 = (2 << 4) | 10,
  pc11 = (2 << 4) | 11,
  pc12 = (2 << 4) | 12,
  pc13 = (2 << 4) | 13,
  pc14 = (2 << 4) | 14,
  pc15 = (2 << 4) | 15,
  pd0 = (3 << 4) | 0,
  pd1 = (3 << 4) | 1,
  pd2 = (3 << 4) | 2,
  pd3 = (3 << 4) | 3,
  pd4 = (3 << 4) | 4,
  pd5 = (3 << 4) | 5,
  pd6 = (3 << 4) | 6,
  pd7 = (3 << 4) | 7,
  pd8 = (3 << 4) | 8,
  pd9 = (3 << 4) | 9,
  pd10 = (3 << 4) | 10,
  pd11 = (3 << 4) | 11,
  pd12 = (3 << 4) | 12,
  pd13 = (3 << 4) | 13,
  pd14 = (3 << 4) | 14,
  pd15 = (3 << 4) | 15,
  pe0 = (4 << 4) | 0,
  pe1 = (4 << 4) | 1,
  pe2 = (4 << 4) | 2,
  pe3 = (4 << 4) | 3,
  pe4 = (4 << 4) | 4,
  pe5 = (4 << 4) | 5,
  pe6 = (4 << 4) | 6,
  pe7 = (4 << 4) | 7,
  pe8 = (4 << 4) | 8,
  pe9 = (4 << 4) | 9,
  pe10 = (4 << 4) | 10,
  pe11 = (4 << 4) | 11,
  pe12 = (4 << 4) | 12,
  pe13 = (4 << 4) | 13,
  pe14 = (4 << 4) | 14,
  pe15 = (4 << 4) | 15,
  pf0 = (5 << 4) | 0,
  pf1 = (5 << 4) | 1,
  pf2 = (5 << 4) | 2,
  pf3 = (5 << 4) | 3,
  pf4 = (5 << 4) | 4,
  pf5 = (5 << 4) | 5,
  pf6 = (5 << 4) | 6,
  pf7 = (5 << 4) | 7,
  pf8 = (5 << 4) | 8,
  pf9 = (5 << 4) | 9,
  pf10 = (5 << 4) | 10,
  pf11 = (5 << 4) | 11,
  pf12 = (5 << 4) | 12,
  pf13 = (5 << 4) | 13,
  pf14 = (5 << 4) | 14,
  pf15 = (5 << 4) | 15,
  pg0 = (6 << 4) | 0,
  pg1 = (6 << 4) | 1,
  pg2 = (6 << 4) | 2,
  pg3 = (6 << 4) | 3,
  pg4 = (6 << 4) | 4,
  pg5 = (6 << 4) | 5,
  pg6 = (6 << 4) | 6,
  pg7 = (6 << 4) | 7,
  pg8 = (6 << 4) | 8,
  pg9 = (6 << 4) | 9,
  pg10 = (6 << 4) | 10,
  pg11 = (6 << 4) | 11,
  pg12 = (6 << 4) | 12,
  pg13 = (6 << 4) | 13,
  pg14 = (6 << 4) | 14,
  pg15 = (6 << 4) | 15,
  ph0 = (7 << 4) | 0,
  ph1 = (7 << 4) | 1,
  ph2 = (7 << 4) | 2,
  ph3 = (7 << 4) | 3,
  ph4 = (7 << 4) | 4,
  ph5 = (7 << 4) | 5,
  ph6 = (7 << 4) | 6,
  ph7 = (7 << 4) | 7,
  ph8 = (7 << 4) | 8,
  ph9 = (7 << 4) | 9,
  ph10 = (7 << 4) | 10,
  ph11 = (7 << 4) | 11,
  ph12 = (7 << 4) | 12,
  ph13 = (7 << 4) | 13,
  ph14 = (7 << 4) | 14,
  ph15 = (7 << 4) | 15,
};

static inline GpioType extract_gpio_type(GpioPinType pin_type) {
  switch (pin_type) {
    case GpioPinType::pa0:
    case GpioPinType::pa1:
    case GpioPinType::pa2:
    case GpioPinType::pa3:
    case GpioPinType::pa4:
    case GpioPinType::pa5:
    case GpioPinType::pa6:
    case GpioPinType::pa7:
    case GpioPinType::pa8:
    case GpioPinType::pa9:
    case GpioPinType::pa10:
    case GpioPinType::pa11:
    case GpioPinType::pa12:
    case GpioPinType::pa13:
    case GpioPinType::pa14:
    case GpioPinType::pa15:
      return GpioType::gpioa;
      [[fallthrough]];
    case GpioPinType::pb0:
    case GpioPinType::pb1:
    case GpioPinType::pb2:
    case GpioPinType::pb3:
    case GpioPinType::pb4:
    case GpioPinType::pb5:
    case GpioPinType::pb6:
    case GpioPinType::pb7:
    case GpioPinType::pb8:
    case GpioPinType::pb9:
    case GpioPinType::pb10:
    case GpioPinType::pb11:
    case GpioPinType::pb12:
    case GpioPinType::pb13:
    case GpioPinType::pb14:
    case GpioPinType::pb15:
      return GpioType::gpiob;
      [[fallthrough]];
    case GpioPinType::pc0:
    case GpioPinType::pc1:
    case GpioPinType::pc2:
    case GpioPinType::pc3:
    case GpioPinType::pc4:
    case GpioPinType::pc5:
    case GpioPinType::pc6:
    case GpioPinType::pc7:
    case GpioPinType::pc8:
    case GpioPinType::pc9:
    case GpioPinType::pc10:
    case GpioPinType::pc11:
    case GpioPinType::pc12:
    case GpioPinType::pc13:
    case GpioPinType::pc14:
    case GpioPinType::pc15:
      return GpioType::gpioc;
      [[fallthrough]];
    case GpioPinType::pd0:
    case GpioPinType::pd1:
    case GpioPinType::pd2:
    case GpioPinType::pd3:
    case GpioPinType::pd4:
    case GpioPinType::pd5:
    case GpioPinType::pd6:
    case GpioPinType::pd7:
    case GpioPinType::pd8:
    case GpioPinType::pd9:
    case GpioPinType::pd10:
    case GpioPinType::pd11:
    case GpioPinType::pd12:
    case GpioPinType::pd13:
    case GpioPinType::pd14:
    case GpioPinType::pd15:
      return GpioType::gpiod;
      [[fallthrough]];
    case GpioPinType::pe0:
    case GpioPinType::pe1:
    case GpioPinType::pe2:
    case GpioPinType::pe3:
    case GpioPinType::pe4:
    case GpioPinType::pe5:
    case GpioPinType::pe6:
    case GpioPinType::pe7:
    case GpioPinType::pe8:
    case GpioPinType::pe9:
    case GpioPinType::pe10:
    case GpioPinType::pe11:
    case GpioPinType::pe12:
    case GpioPinType::pe13:
    case GpioPinType::pe14:
    case GpioPinType::pe15:
      return GpioType::gpioe;
      [[fallthrough]];
    case GpioPinType::pf0:
    case GpioPinType::pf1:
    case GpioPinType::pf2:
    case GpioPinType::pf3:
    case GpioPinType::pf4:
    case GpioPinType::pf5:
    case GpioPinType::pf6:
    case GpioPinType::pf7:
    case GpioPinType::pf8:
    case GpioPinType::pf9:
    case GpioPinType::pf10:
    case GpioPinType::pf11:
    case GpioPinType::pf12:
    case GpioPinType::pf13:
    case GpioPinType::pf14:
    case GpioPinType::pf15:
      return GpioType::gpiof;
      [[fallthrough]];
    case GpioPinType::pg0:
    case GpioPinType::pg1:
    case GpioPinType::pg2:
    case GpioPinType::pg3:
    case GpioPinType::pg4:
    case GpioPinType::pg5:
    case GpioPinType::pg6:
    case GpioPinType::pg7:
    case GpioPinType::pg8:
    case GpioPinType::pg9:
    case GpioPinType::pg10:
    case GpioPinType::pg11:
    case GpioPinType::pg12:
    case GpioPinType::pg13:
    case GpioPinType::pg14:
    case GpioPinType::pg15:
      return GpioType::gpiog;
      [[fallthrough]];
    case GpioPinType::ph0:
    case GpioPinType::ph1:
    case GpioPinType::ph2:
    case GpioPinType::ph3:
    case GpioPinType::ph4:
    case GpioPinType::ph5:
    case GpioPinType::ph6:
    case GpioPinType::ph7:
    case GpioPinType::ph8:
    case GpioPinType::ph9:
    case GpioPinType::ph10:
    case GpioPinType::ph11:
    case GpioPinType::ph12:
    case GpioPinType::ph13:
    case GpioPinType::ph14:
    case GpioPinType::ph15:
      return GpioType::gpioh;
      [[fallthrough]];
  }
}

static inline uint8_t extract_pin_idx(GpioPinType pin_type) {
  switch (pin_type) {
    case GpioPinType::pa0:
      return 0;
    case GpioPinType::pa1:
      return 1;
    case GpioPinType::pa2:
      return 2;
    case GpioPinType::pa3:
      return 3;
    case GpioPinType::pa4:
      return 4;
    case GpioPinType::pa5:
      return 5;
    case GpioPinType::pa6:
      return 6;
    case GpioPinType::pa7:
      return 7;
    case GpioPinType::pa8:
      return 8;
    case GpioPinType::pa9:
      return 9;
    case GpioPinType::pa10:
      return 10;
    case GpioPinType::pa11:
      return 11;
    case GpioPinType::pa12:
      return 12;
    case GpioPinType::pa13:
      return 13;
    case GpioPinType::pa14:
      return 14;
    case GpioPinType::pa15:
      return 15;
    case GpioPinType::pb0:
      return 0;
    case GpioPinType::pb1:
      return 1;
    case GpioPinType::pb2:
      return 2;
    case GpioPinType::pb3:
      return 3;
    case GpioPinType::pb4:
      return 4;
    case GpioPinType::pb5:
      return 5;
    case GpioPinType::pb6:
      return 6;
    case GpioPinType::pb7:
      return 7;
    case GpioPinType::pb8:
      return 8;
    case GpioPinType::pb9:
      return 9;
    case GpioPinType::pb10:
      return 10;
    case GpioPinType::pb11:
      return 11;
    case GpioPinType::pb12:
      return 12;
    case GpioPinType::pb13:
      return 13;
    case GpioPinType::pb14:
      return 14;
    case GpioPinType::pb15:
      return 15;
    case GpioPinType::pc0:
      return 0;
    case GpioPinType::pc1:
      return 1;
    case GpioPinType::pc2:
      return 2;
    case GpioPinType::pc3:
      return 3;
    case GpioPinType::pc4:
      return 4;
    case GpioPinType::pc5:
      return 5;
    case GpioPinType::pc6:
      return 6;
    case GpioPinType::pc7:
      return 7;
    case GpioPinType::pc8:
      return 8;
    case GpioPinType::pc9:
      return 9;
    case GpioPinType::pc10:
      return 10;
    case GpioPinType::pc11:
      return 11;
    case GpioPinType::pc12:
      return 12;
    case GpioPinType::pc13:
      return 13;
    case GpioPinType::pc14:
      return 14;
    case GpioPinType::pc15:
      return 15;
    case GpioPinType::pd0:
      return 0;
    case GpioPinType::pd1:
      return 1;
    case GpioPinType::pd2:
      return 2;
    case GpioPinType::pd3:
      return 3;
    case GpioPinType::pd4:
      return 4;
    case GpioPinType::pd5:
      return 5;
    case GpioPinType::pd6:
      return 6;
    case GpioPinType::pd7:
      return 7;
    case GpioPinType::pd8:
      return 8;
    case GpioPinType::pd9:
      return 9;
    case GpioPinType::pd10:
      return 10;
    case GpioPinType::pd11:
      return 11;
    case GpioPinType::pd12:
      return 12;
    case GpioPinType::pd13:
      return 13;
    case GpioPinType::pd14:
      return 14;
    case GpioPinType::pd15:
      return 15;
    case GpioPinType::pe0:
      return 0;
    case GpioPinType::pe1:
      return 1;
    case GpioPinType::pe2:
      return 2;
    case GpioPinType::pe3:
      return 3;
    case GpioPinType::pe4:
      return 4;
    case GpioPinType::pe5:
      return 5;
    case GpioPinType::pe6:
      return 6;
    case GpioPinType::pe7:
      return 7;
    case GpioPinType::pe8:
      return 8;
    case GpioPinType::pe9:
      return 9;
    case GpioPinType::pe10:
      return 10;
    case GpioPinType::pe11:
      return 11;
    case GpioPinType::pe12:
      return 12;
    case GpioPinType::pe13:
      return 13;
    case GpioPinType::pe14:
      return 14;
    case GpioPinType::pe15:
      return 15;
    case GpioPinType::pf0:
      return 0;
    case GpioPinType::pf1:
      return 1;
    case GpioPinType::pf2:
      return 2;
    case GpioPinType::pf3:
      return 3;
    case GpioPinType::pf4:
      return 4;
    case GpioPinType::pf5:
      return 5;
    case GpioPinType::pf6:
      return 6;
    case GpioPinType::pf7:
      return 7;
    case GpioPinType::pf8:
      return 8;
    case GpioPinType::pf9:
      return 9;
    case GpioPinType::pf10:
      return 10;
    case GpioPinType::pf11:
      return 11;
    case GpioPinType::pf12:
      return 12;
    case GpioPinType::pf13:
      return 13;
    case GpioPinType::pf14:
      return 14;
    case GpioPinType::pf15:
      return 15;
    case GpioPinType::pg0:
      return 0;
    case GpioPinType::pg1:
      return 1;
    case GpioPinType::pg2:
      return 2;
    case GpioPinType::pg3:
      return 3;
    case GpioPinType::pg4:
      return 4;
    case GpioPinType::pg5:
      return 5;
    case GpioPinType::pg6:
      return 6;
    case GpioPinType::pg7:
      return 7;
    case GpioPinType::pg8:
      return 8;
    case GpioPinType::pg9:
      return 9;
    case GpioPinType::pg10:
      return 10;
    case GpioPinType::pg11:
      return 11;
    case GpioPinType::pg12:
      return 12;
    case GpioPinType::pg13:
      return 13;
    case GpioPinType::pg14:
      return 14;
    case GpioPinType::pg15:
      return 15;
    case GpioPinType::ph0:
      return 0;
    case GpioPinType::ph1:
      return 1;
    case GpioPinType::ph2:
      return 2;
    case GpioPinType::ph3:
      return 3;
    case GpioPinType::ph4:
      return 4;
    case GpioPinType::ph5:
      return 5;
    case GpioPinType::ph6:
      return 6;
    case GpioPinType::ph7:
      return 7;
    case GpioPinType::ph8:
      return 8;
    case GpioPinType::ph9:
      return 9;
    case GpioPinType::ph10:
      return 10;
    case GpioPinType::ph11:
      return 11;
    case GpioPinType::ph12:
      return 12;
    case GpioPinType::ph13:
      return 13;
    case GpioPinType::ph14:
      return 14;
    case GpioPinType::ph15:
      return 15;
  }
}

enum class BusType : uint8_t {
  apb1 = 0,
  ahb1,
  ahb2,
  ahb3,
  apb2,
};

const std::array<__IO uint32_t*, 5> STM32_BUS_TO_ENR_ADDRESS = {
  &(RCC->APB1ENR),
  &(RCC->AHB1ENR),
  &(RCC->AHB2ENR),
  &(RCC->AHB3ENR),
  &(RCC->APB2ENR),
};

const std::array<__IO uint32_t*, 5> STM32_BUS_TO_RSTR_ADDRESS = {
  &(RCC->APB1RSTR),
  &(RCC->AHB1RSTR),
  &(RCC->AHB2RSTR),
  &(RCC->AHB3RSTR),
  &(RCC->APB2RSTR),
};

#include <igb_stm32/base/_info.hpp>

constexpr struct PeriphInfo {
  const RccInfo rcc {
    .periph_type = PeriphType::rcc,
    .p_rcc = RCC,
  };
  const std::array<GpioInfo, 8> gpio {
    GpioInfo {
      .periph_type = PeriphType::gpioa,
      .p_gpio = GPIOA,
      .bus = PeriphBusInfo { BusType::ahb1, (uint32_t)1 << 0},
    },
    GpioInfo {
      .periph_type = PeriphType::gpiob,
      .p_gpio = GPIOB,
      .bus = PeriphBusInfo { BusType::ahb1, (uint32_t)1 << 1},
    },
    GpioInfo {
      .periph_type = PeriphType::gpioc,
      .p_gpio = GPIOC,
      .bus = PeriphBusInfo { BusType::ahb1, (uint32_t)1 << 2},
    },
    GpioInfo {
      .periph_type = PeriphType::gpiod,
      .p_gpio = GPIOD,
      .bus = PeriphBusInfo { BusType::ahb1, (uint32_t)1 << 3},
    },
    GpioInfo {
      .periph_type = PeriphType::gpioe,
      .p_gpio = GPIOE,
      .bus = PeriphBusInfo { BusType::ahb1, (uint32_t)1 << 4},
    },
    GpioInfo {
      .periph_type = PeriphType::gpiof,
      .p_gpio = GPIOF,
      .bus = PeriphBusInfo { BusType::ahb1, (uint32_t)1 << 5},
    },
    GpioInfo {
      .periph_type = PeriphType::gpiog,
      .p_gpio = GPIOG,
      .bus = PeriphBusInfo { BusType::ahb1, (uint32_t)1 << 6},
    },
    GpioInfo {
      .periph_type = PeriphType::gpioh,
      .p_gpio = GPIOH,
      .bus = PeriphBusInfo { BusType::ahb1, (uint32_t)1 << 7},
    },
  };
  const std::array<SpiInfo, 4> spi {
    SpiInfo {
      .periph_type = PeriphType::spi1,
      .p_spi = SPI1,
      .bus = PeriphBusInfo { BusType::apb2, (uint32_t)1 << 12},
    },
    SpiInfo {
      .periph_type = PeriphType::spi2,
      .p_spi = SPI2,
      .bus = PeriphBusInfo { BusType::apb1, (uint32_t)1 << 14},
    },
    SpiInfo {
      .periph_type = PeriphType::spi3,
      .p_spi = SPI3,
      .bus = PeriphBusInfo { BusType::apb1, (uint32_t)1 << 15},
    },
    SpiInfo {
      .periph_type = PeriphType::spi4,
      .p_spi = SPI4,
      .bus = PeriphBusInfo { BusType::apb2, (uint32_t)1 << 13},
    },
  };
  const std::array<AdcInfo, 3> adc {
    AdcInfo {
      .periph_type = PeriphType::adc1,
      .p_adc = ADC1,
      .bus = PeriphBusInfo { BusType::apb2, (uint32_t)1 << 8},
    },
    AdcInfo {
      .periph_type = PeriphType::adc2,
      .p_adc = ADC2,
      .bus = PeriphBusInfo { BusType::apb2, (uint32_t)1 << 9},
    },
    AdcInfo {
      .periph_type = PeriphType::adc3,
      .p_adc = ADC3,
      .bus = PeriphBusInfo { BusType::apb2, (uint32_t)1 << 10},
    },
  };
  const std::array<UsartInfo, 6> usart {
    UsartInfo {
      .periph_type = PeriphType::usart1,
      .p_usart = USART1,
      .bus = PeriphBusInfo { BusType::apb2, (uint32_t)1 << 4},
    },
    UsartInfo {
      .periph_type = PeriphType::usart2,
      .p_usart = USART2,
      .bus = PeriphBusInfo { BusType::apb1, (uint32_t)1 << 17},
    },
    UsartInfo {
      .periph_type = PeriphType::usart3,
      .p_usart = USART3,
      .bus = PeriphBusInfo { BusType::apb1, (uint32_t)1 << 18},
    },
    UsartInfo {
      .periph_type = PeriphType::uart4,
      .p_usart = UART4,
      .bus = PeriphBusInfo { BusType::apb1, (uint32_t)1 << 19},
    },
    UsartInfo {
      .periph_type = PeriphType::uart5,
      .p_usart = UART5,
      .bus = PeriphBusInfo { BusType::apb1, (uint32_t)1 << 20},
    },
    UsartInfo {
      .periph_type = PeriphType::usart6,
      .p_usart = USART6,
      .bus = PeriphBusInfo { BusType::apb2, (uint32_t)1 << 5},
    },
  };
  const std::array<DacInfo, 1> dac {
    DacInfo {
      .periph_type = PeriphType::dac1,
      .p_dac = DAC1,
      .bus = PeriphBusInfo { BusType::apb1, (uint32_t)1 << 29},
    },
  };
  const std::array<I2cInfo, 3> i2c {
    I2cInfo {
      .periph_type = PeriphType::i2c1,
      .p_i2c = I2C1,
      .bus = PeriphBusInfo { BusType::apb1, (uint32_t)1 << 21},
    },
    I2cInfo {
      .periph_type = PeriphType::i2c2,
      .p_i2c = I2C2,
      .bus = PeriphBusInfo { BusType::apb1, (uint32_t)1 << 22},
    },
    I2cInfo {
      .periph_type = PeriphType::i2c3,
      .p_i2c = I2C3,
      .bus = PeriphBusInfo { BusType::apb1, (uint32_t)1 << 23},
    },
  };
  const std::array<TimInfo, 14> tim {
    TimInfo {
      .periph_type = PeriphType::tim1,
      .category = TimCategory::ADVANCED,
      .p_tim = TIM1,
      .irqn = TIM1_UP_TIM10_IRQn,
      .bus = PeriphBusInfo { BusType::apb2, (uint32_t)1 << 0},
    },
    TimInfo {
      .periph_type = PeriphType::tim2,
      .category = TimCategory::GENERAL,
      .p_tim = TIM2,
      .irqn = TIM2_IRQn,
      .bus = PeriphBusInfo { BusType::apb1, (uint32_t)1 << 0},
    },
    TimInfo {
      .periph_type = PeriphType::tim3,
      .category = TimCategory::GENERAL,
      .p_tim = TIM3,
      .irqn = TIM3_IRQn,
      .bus = PeriphBusInfo { BusType::apb1, (uint32_t)1 << 1},
    },
    TimInfo {
      .periph_type = PeriphType::tim4,
      .category = TimCategory::GENERAL,
      .p_tim = TIM4,
      .irqn = TIM4_IRQn,
      .bus = PeriphBusInfo { BusType::apb1, (uint32_t)1 << 2},
    },
    TimInfo {
      .periph_type = PeriphType::tim5,
      .category = TimCategory::GENERAL,
      .p_tim = TIM5,
      .irqn = TIM5_IRQn,
      .bus = PeriphBusInfo { BusType::apb1, (uint32_t)1 << 3},
    },
    TimInfo {
      .periph_type = PeriphType::tim6,
      .category = TimCategory::BASIC,
      .p_tim = TIM6,
      .irqn = TIM6_DAC_IRQn,
      .bus = PeriphBusInfo { BusType::apb1, (uint32_t)1 << 4},
    },
    TimInfo {
      .periph_type = PeriphType::tim7,
      .category = TimCategory::BASIC,
      .p_tim = TIM7,
      .irqn = TIM7_IRQn,
      .bus = PeriphBusInfo { BusType::apb1, (uint32_t)1 << 5},
    },
    TimInfo {
      .periph_type = PeriphType::tim8,
      .category = TimCategory::ADVANCED,
      .p_tim = TIM8,
      .irqn = TIM8_UP_TIM13_IRQn,
      .bus = PeriphBusInfo { BusType::apb2, (uint32_t)1 << 1},
    },
    TimInfo {
      .periph_type = PeriphType::tim9,
      .category = TimCategory::GENERAL,
      .p_tim = TIM9,
      .irqn = TIM1_BRK_TIM9_IRQn,
      .bus = PeriphBusInfo { BusType::apb2, (uint32_t)1 << 16},
    },
    TimInfo {
      .periph_type = PeriphType::tim10,
      .category = TimCategory::GENERAL,
      .p_tim = TIM10,
      .irqn = TIM1_UP_TIM10_IRQn,
      .bus = PeriphBusInfo { BusType::apb2, (uint32_t)1 << 17},
    },
    TimInfo {
      .periph_type = PeriphType::tim11,
      .category = TimCategory::GENERAL,
      .p_tim = TIM11,
      .irqn = TIM1_TRG_COM_TIM11_IRQn,
      .bus = PeriphBusInfo { BusType::apb2, (uint32_t)1 << 18},
    },
    TimInfo {
      .periph_type = PeriphType::tim12,
      .category = TimCategory::GENERAL,
      .p_tim = TIM12,
      .irqn = TIM8_BRK_TIM12_IRQn,
      .bus = PeriphBusInfo { BusType::apb1, (uint32_t)1 << 6},
    },
    TimInfo {
      .periph_type = PeriphType::tim13,
      .category = TimCategory::GENERAL,
      .p_tim = TIM13,
      .irqn = TIM8_UP_TIM13_IRQn,
      .bus = PeriphBusInfo { BusType::apb1, (uint32_t)1 << 7},
    },
    TimInfo {
      .periph_type = PeriphType::tim14,
      .category = TimCategory::GENERAL,
      .p_tim = TIM14,
      .irqn = TIM8_TRG_COM_TIM14_IRQn,
      .bus = PeriphBusInfo { BusType::apb1, (uint32_t)1 << 8},
    },
  };
} STM32_PERIPH_INFO;


enum class GpioAf : uint8_t {
  af0 = 0,
  af1,
  af2,
  af3,
  af4,
  af5,
  af6,
  af7,
  af8,
  af9,
  af10,
  af11,
  af12,
  af13,
};

static inline std::optional<GpioAf> get_af_idx(PeriphType periph_type, GpioPinType gpio_pin) {
  switch (gpio_pin) {
    case GpioPinType::pa0:
      switch (periph_type) {
        case PeriphType::tim2:
          return GpioAf::af1;
        case PeriphType::tim5:
          return GpioAf::af2;
        case PeriphType::tim8:
          return GpioAf::af3;
        case PeriphType::usart2:
          return GpioAf::af7;
        case PeriphType::uart4:
          return GpioAf::af8;
        default:
          break;
      }
      break;
    case GpioPinType::pa1:
      switch (periph_type) {
        case PeriphType::tim2:
          return GpioAf::af1;
        case PeriphType::tim5:
          return GpioAf::af2;
        case PeriphType::usart2:
          return GpioAf::af7;
        case PeriphType::uart4:
          return GpioAf::af8;
        default:
          break;
      }
      break;
    case GpioPinType::pa2:
      switch (periph_type) {
        case PeriphType::tim2:
          return GpioAf::af1;
        case PeriphType::tim5:
          return GpioAf::af2;
        case PeriphType::tim9:
          return GpioAf::af3;
        case PeriphType::usart2:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pa3:
      switch (periph_type) {
        case PeriphType::tim2:
          return GpioAf::af1;
        case PeriphType::tim5:
          return GpioAf::af2;
        case PeriphType::tim9:
          return GpioAf::af3;
        case PeriphType::usart2:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pa4:
      switch (periph_type) {
        case PeriphType::spi1:
          return GpioAf::af5;
        case PeriphType::spi3:
          return GpioAf::af6;
        case PeriphType::usart2:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pa5:
      switch (periph_type) {
        case PeriphType::tim2:
          return GpioAf::af1;
        case PeriphType::tim8:
          return GpioAf::af3;
        case PeriphType::spi1:
          return GpioAf::af5;
        default:
          break;
      }
      break;
    case GpioPinType::pa6:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        case PeriphType::tim3:
          return GpioAf::af2;
        case PeriphType::tim8:
          return GpioAf::af3;
        case PeriphType::spi1:
          return GpioAf::af5;
        case PeriphType::tim13:
          return GpioAf::af9;
        default:
          break;
      }
      break;
    case GpioPinType::pa7:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        case PeriphType::tim3:
          return GpioAf::af2;
        case PeriphType::tim8:
          return GpioAf::af3;
        case PeriphType::spi1:
          return GpioAf::af5;
        case PeriphType::tim14:
          return GpioAf::af9;
        default:
          break;
      }
      break;
    case GpioPinType::pa8:
      switch (periph_type) {
        case PeriphType::rcc:
          return GpioAf::af0;
        case PeriphType::tim1:
          return GpioAf::af1;
        case PeriphType::i2c3:
          return GpioAf::af4;
        case PeriphType::usart1:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pa9:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        case PeriphType::i2c3:
          return GpioAf::af4;
        case PeriphType::spi2:
          return GpioAf::af5;
        case PeriphType::usart1:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pa10:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        case PeriphType::usart1:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pa11:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        case PeriphType::usart1:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pa12:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        case PeriphType::usart1:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pa13:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pa14:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pa15:
      switch (periph_type) {
        case PeriphType::tim2:
          return GpioAf::af1;
        case PeriphType::spi1:
          return GpioAf::af5;
        case PeriphType::spi3:
          return GpioAf::af6;
        case PeriphType::uart4:
          return GpioAf::af8;
        default:
          break;
      }
      break;
    case GpioPinType::pb0:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        case PeriphType::tim3:
          return GpioAf::af2;
        case PeriphType::tim8:
          return GpioAf::af3;
        case PeriphType::spi3:
          return GpioAf::af7;
        case PeriphType::uart4:
          return GpioAf::af8;
        default:
          break;
      }
      break;
    case GpioPinType::pb1:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        case PeriphType::tim3:
          return GpioAf::af2;
        case PeriphType::tim8:
          return GpioAf::af3;
        default:
          break;
      }
      break;
    case GpioPinType::pb2:
      switch (periph_type) {
        case PeriphType::tim2:
          return GpioAf::af1;
        case PeriphType::spi3:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pb3:
      switch (periph_type) {
        case PeriphType::tim2:
          return GpioAf::af1;
        case PeriphType::i2c2:
          return GpioAf::af4;
        case PeriphType::spi1:
          return GpioAf::af5;
        case PeriphType::spi3:
          return GpioAf::af6;
        default:
          break;
      }
      break;
    case GpioPinType::pb4:
      switch (periph_type) {
        case PeriphType::tim3:
          return GpioAf::af2;
        case PeriphType::i2c3:
          return GpioAf::af4;
        case PeriphType::spi1:
          return GpioAf::af5;
        case PeriphType::spi3:
          return GpioAf::af6;
        case PeriphType::spi2:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pb5:
      switch (periph_type) {
        case PeriphType::tim3:
          return GpioAf::af2;
        case PeriphType::i2c1:
          return GpioAf::af4;
        case PeriphType::spi1:
          return GpioAf::af5;
        case PeriphType::spi3:
          return GpioAf::af6;
        default:
          break;
      }
      break;
    case GpioPinType::pb6:
      switch (periph_type) {
        case PeriphType::tim4:
          return GpioAf::af2;
        case PeriphType::i2c1:
          return GpioAf::af4;
        case PeriphType::usart1:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pb7:
      switch (periph_type) {
        case PeriphType::tim4:
          return GpioAf::af2;
        case PeriphType::i2c1:
          return GpioAf::af4;
        case PeriphType::usart1:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pb8:
      switch (periph_type) {
        case PeriphType::tim2:
          return GpioAf::af1;
        case PeriphType::tim4:
          return GpioAf::af2;
        case PeriphType::tim10:
          return GpioAf::af3;
        case PeriphType::i2c1:
          return GpioAf::af4;
        default:
          break;
      }
      break;
    case GpioPinType::pb9:
      switch (periph_type) {
        case PeriphType::tim2:
          return GpioAf::af1;
        case PeriphType::tim4:
          return GpioAf::af2;
        case PeriphType::tim11:
          return GpioAf::af3;
        case PeriphType::i2c1:
          return GpioAf::af4;
        case PeriphType::spi2:
          return GpioAf::af5;
        default:
          break;
      }
      break;
    case GpioPinType::pb10:
      switch (periph_type) {
        case PeriphType::tim2:
          return GpioAf::af1;
        case PeriphType::i2c2:
          return GpioAf::af4;
        case PeriphType::spi2:
          return GpioAf::af5;
        case PeriphType::usart3:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pb11:
      switch (periph_type) {
        case PeriphType::tim2:
          return GpioAf::af1;
        case PeriphType::i2c2:
          return GpioAf::af4;
        case PeriphType::usart3:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pb12:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        case PeriphType::i2c2:
          return GpioAf::af4;
        case PeriphType::spi2:
          return GpioAf::af5;
        case PeriphType::usart3:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pb13:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        case PeriphType::spi2:
          return GpioAf::af5;
        case PeriphType::usart3:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pb14:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        case PeriphType::tim8:
          return GpioAf::af3;
        case PeriphType::spi2:
          return GpioAf::af5;
        case PeriphType::usart3:
          return GpioAf::af7;
        case PeriphType::tim12:
          return GpioAf::af9;
        default:
          break;
      }
      break;
    case GpioPinType::pb15:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        case PeriphType::tim8:
          return GpioAf::af3;
        case PeriphType::spi2:
          return GpioAf::af5;
        case PeriphType::tim12:
          return GpioAf::af9;
        default:
          break;
      }
      break;
    case GpioPinType::pc0:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pc1:
      switch (periph_type) {
        case PeriphType::spi3:
          return GpioAf::af5;
        case PeriphType::spi2:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pc2:
      switch (periph_type) {
        case PeriphType::spi2:
          return GpioAf::af5;
        default:
          break;
      }
      break;
    case GpioPinType::pc3:
      switch (periph_type) {
        case PeriphType::spi2:
          return GpioAf::af5;
        default:
          break;
      }
      break;
    case GpioPinType::pc4:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pc5:
      switch (periph_type) {
        case PeriphType::usart3:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pc6:
      switch (periph_type) {
        case PeriphType::tim3:
          return GpioAf::af2;
        case PeriphType::tim8:
          return GpioAf::af3;
        case PeriphType::usart6:
          return GpioAf::af8;
        default:
          break;
      }
      break;
    case GpioPinType::pc7:
      switch (periph_type) {
        case PeriphType::tim3:
          return GpioAf::af2;
        case PeriphType::tim8:
          return GpioAf::af3;
        case PeriphType::spi2:
          return GpioAf::af5;
        case PeriphType::usart6:
          return GpioAf::af8;
        default:
          break;
      }
      break;
    case GpioPinType::pc8:
      switch (periph_type) {
        case PeriphType::tim3:
          return GpioAf::af2;
        case PeriphType::tim8:
          return GpioAf::af3;
        case PeriphType::uart5:
          return GpioAf::af7;
        case PeriphType::usart6:
          return GpioAf::af8;
        default:
          break;
      }
      break;
    case GpioPinType::pc9:
      switch (periph_type) {
        case PeriphType::rcc:
          return GpioAf::af0;
        case PeriphType::tim3:
          return GpioAf::af2;
        case PeriphType::tim8:
          return GpioAf::af3;
        case PeriphType::i2c3:
          return GpioAf::af4;
        case PeriphType::uart5:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pc10:
      switch (periph_type) {
        case PeriphType::spi3:
          return GpioAf::af6;
        case PeriphType::usart3:
          return GpioAf::af7;
        case PeriphType::uart4:
          return GpioAf::af8;
        default:
          break;
      }
      break;
    case GpioPinType::pc11:
      switch (periph_type) {
        case PeriphType::spi3:
          return GpioAf::af6;
        case PeriphType::usart3:
          return GpioAf::af7;
        case PeriphType::uart4:
          return GpioAf::af8;
        default:
          break;
      }
      break;
    case GpioPinType::pc12:
      switch (periph_type) {
        case PeriphType::i2c2:
          return GpioAf::af4;
        case PeriphType::spi3:
          return GpioAf::af6;
        case PeriphType::usart3:
          return GpioAf::af7;
        case PeriphType::uart5:
          return GpioAf::af8;
        default:
          break;
      }
      break;
    case GpioPinType::pd0:
      switch (periph_type) {
        case PeriphType::spi4:
          return GpioAf::af5;
        case PeriphType::spi3:
          return GpioAf::af6;
        default:
          break;
      }
      break;
    case GpioPinType::pd1:
      switch (periph_type) {
        case PeriphType::spi2:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pd2:
      switch (periph_type) {
        case PeriphType::tim3:
          return GpioAf::af2;
        case PeriphType::uart5:
          return GpioAf::af8;
        default:
          break;
      }
      break;
    case GpioPinType::pd3:
      switch (periph_type) {
        case PeriphType::spi2:
          return GpioAf::af5;
        case PeriphType::usart2:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pd4:
      switch (periph_type) {
        case PeriphType::usart2:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pd5:
      switch (periph_type) {
        case PeriphType::usart2:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pd6:
      switch (periph_type) {
        case PeriphType::spi3:
          return GpioAf::af5;
        case PeriphType::usart2:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pd7:
      switch (periph_type) {
        case PeriphType::usart2:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pd8:
      switch (periph_type) {
        case PeriphType::usart3:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pd9:
      switch (periph_type) {
        case PeriphType::usart3:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pd10:
      switch (periph_type) {
        case PeriphType::usart3:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pd11:
      switch (periph_type) {
        case PeriphType::usart3:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pd12:
      switch (periph_type) {
        case PeriphType::tim4:
          return GpioAf::af2;
        case PeriphType::usart3:
          return GpioAf::af7;
        default:
          break;
      }
      break;
    case GpioPinType::pd13:
      switch (periph_type) {
        case PeriphType::tim4:
          return GpioAf::af2;
        default:
          break;
      }
      break;
    case GpioPinType::pd14:
      switch (periph_type) {
        case PeriphType::tim4:
          return GpioAf::af2;
        default:
          break;
      }
      break;
    case GpioPinType::pd15:
      switch (periph_type) {
        case PeriphType::tim4:
          return GpioAf::af2;
        default:
          break;
      }
      break;
    case GpioPinType::pe0:
      switch (periph_type) {
        case PeriphType::tim4:
          return GpioAf::af2;
        default:
          break;
      }
      break;
    case GpioPinType::pe1:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pe2:
      switch (periph_type) {
        case PeriphType::spi4:
          return GpioAf::af5;
        default:
          break;
      }
      break;
    case GpioPinType::pe3:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pe4:
      switch (periph_type) {
        case PeriphType::spi4:
          return GpioAf::af5;
        default:
          break;
      }
      break;
    case GpioPinType::pe5:
      switch (periph_type) {
        case PeriphType::tim9:
          return GpioAf::af3;
        case PeriphType::spi4:
          return GpioAf::af5;
        default:
          break;
      }
      break;
    case GpioPinType::pe6:
      switch (periph_type) {
        case PeriphType::tim9:
          return GpioAf::af3;
        case PeriphType::spi4:
          return GpioAf::af5;
        default:
          break;
      }
      break;
    case GpioPinType::pe7:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        case PeriphType::uart5:
          return GpioAf::af8;
        default:
          break;
      }
      break;
    case GpioPinType::pe8:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        case PeriphType::uart5:
          return GpioAf::af8;
        default:
          break;
      }
      break;
    case GpioPinType::pe9:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        default:
          break;
      }
      break;
    case GpioPinType::pe10:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        default:
          break;
      }
      break;
    case GpioPinType::pe11:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        case PeriphType::spi4:
          return GpioAf::af5;
        default:
          break;
      }
      break;
    case GpioPinType::pe12:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        case PeriphType::spi4:
          return GpioAf::af5;
        default:
          break;
      }
      break;
    case GpioPinType::pe13:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        case PeriphType::spi4:
          return GpioAf::af5;
        default:
          break;
      }
      break;
    case GpioPinType::pe14:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        case PeriphType::spi4:
          return GpioAf::af5;
        default:
          break;
      }
      break;
    case GpioPinType::pe15:
      switch (periph_type) {
        case PeriphType::tim1:
          return GpioAf::af1;
        default:
          break;
      }
      break;
    case GpioPinType::pf0:
      switch (periph_type) {
        case PeriphType::i2c2:
          return GpioAf::af4;
        default:
          break;
      }
      break;
    case GpioPinType::pf1:
      switch (periph_type) {
        case PeriphType::i2c2:
          return GpioAf::af4;
        default:
          break;
      }
      break;
    case GpioPinType::pf2:
      switch (periph_type) {
        case PeriphType::i2c2:
          return GpioAf::af4;
        default:
          break;
      }
      break;
    case GpioPinType::pf3:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pf4:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pf5:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pf6:
      switch (periph_type) {
        case PeriphType::tim10:
          return GpioAf::af3;
        default:
          break;
      }
      break;
    case GpioPinType::pf7:
      switch (periph_type) {
        case PeriphType::tim11:
          return GpioAf::af3;
        default:
          break;
      }
      break;
    case GpioPinType::pf8:
      switch (periph_type) {
        case PeriphType::tim13:
          return GpioAf::af9;
        default:
          break;
      }
      break;
    case GpioPinType::pf9:
      switch (periph_type) {
        case PeriphType::tim14:
          return GpioAf::af9;
        default:
          break;
      }
      break;
    case GpioPinType::pf10:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pf11:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pf12:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pf13:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pf14:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pf15:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pg0:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pg1:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pg2:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pg3:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pg4:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pg5:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pg6:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pg7:
      switch (periph_type) {
        case PeriphType::usart6:
          return GpioAf::af8;
        default:
          break;
      }
      break;
    case GpioPinType::pg8:
      switch (periph_type) {
        case PeriphType::usart6:
          return GpioAf::af8;
        default:
          break;
      }
      break;
    case GpioPinType::pg9:
      switch (periph_type) {
        case PeriphType::usart6:
          return GpioAf::af8;
        default:
          break;
      }
      break;
    case GpioPinType::pg10:
      switch (periph_type) {
        default:
          break;
      }
      break;
    case GpioPinType::pg11:
      switch (periph_type) {
        case PeriphType::spi4:
          return GpioAf::af6;
        default:
          break;
      }
      break;
    case GpioPinType::pg12:
      switch (periph_type) {
        case PeriphType::spi4:
          return GpioAf::af6;
        case PeriphType::usart6:
          return GpioAf::af8;
        default:
          break;
      }
      break;
    case GpioPinType::pg13:
      switch (periph_type) {
        case PeriphType::spi4:
          return GpioAf::af6;
        case PeriphType::usart6:
          return GpioAf::af8;
        default:
          break;
      }
      break;
    case GpioPinType::pg14:
      switch (periph_type) {
        case PeriphType::spi4:
          return GpioAf::af6;
        case PeriphType::usart6:
          return GpioAf::af8;
        default:
          break;
      }
      break;
    case GpioPinType::pg15:
      switch (periph_type) {
        case PeriphType::usart6:
          return GpioAf::af8;
        default:
          break;
      }
      break;
    default:
      break;
  }
  return std::nullopt;
}

template<typename T>
static inline std::optional<PeriphType> as_periph_type(T type) {
  return std::nullopt;
}

template<>
inline std::optional<PeriphType> as_periph_type(GpioType type) {
  switch (type) {
    case GpioType::gpioa:
      return PeriphType::gpioa;
    case GpioType::gpiob:
      return PeriphType::gpiob;
    case GpioType::gpioc:
      return PeriphType::gpioc;
    case GpioType::gpiod:
      return PeriphType::gpiod;
    case GpioType::gpioe:
      return PeriphType::gpioe;
    case GpioType::gpiof:
      return PeriphType::gpiof;
    case GpioType::gpiog:
      return PeriphType::gpiog;
    case GpioType::gpioh:
      return PeriphType::gpioh;
  }
  return std::nullopt;
}
template<>
inline std::optional<PeriphType> as_periph_type(SpiType type) {
  switch (type) {
    case SpiType::spi1:
      return PeriphType::spi1;
    case SpiType::spi2:
      return PeriphType::spi2;
    case SpiType::spi3:
      return PeriphType::spi3;
    case SpiType::spi4:
      return PeriphType::spi4;
  }
  return std::nullopt;
}
template<>
inline std::optional<PeriphType> as_periph_type(AdcType type) {
  switch (type) {
    case AdcType::adc1:
      return PeriphType::adc1;
    case AdcType::adc2:
      return PeriphType::adc2;
    case AdcType::adc3:
      return PeriphType::adc3;
  }
  return std::nullopt;
}
template<>
inline std::optional<PeriphType> as_periph_type(UsartType type) {
  switch (type) {
    case UsartType::usart1:
      return PeriphType::usart1;
    case UsartType::usart2:
      return PeriphType::usart2;
    case UsartType::usart3:
      return PeriphType::usart3;
    case UsartType::uart4:
      return PeriphType::uart4;
    case UsartType::uart5:
      return PeriphType::uart5;
    case UsartType::usart6:
      return PeriphType::usart6;
  }
  return std::nullopt;
}
template<>
inline std::optional<PeriphType> as_periph_type(DacType type) {
  switch (type) {
    case DacType::dac1:
      return PeriphType::dac1;
  }
  return std::nullopt;
}
template<>
inline std::optional<PeriphType> as_periph_type(I2cType type) {
  switch (type) {
    case I2cType::i2c1:
      return PeriphType::i2c1;
    case I2cType::i2c2:
      return PeriphType::i2c2;
    case I2cType::i2c3:
      return PeriphType::i2c3;
  }
  return std::nullopt;
}
template<>
inline std::optional<PeriphType> as_periph_type(TimType type) {
  switch (type) {
    case TimType::tim1:
      return PeriphType::tim1;
    case TimType::tim2:
      return PeriphType::tim2;
    case TimType::tim3:
      return PeriphType::tim3;
    case TimType::tim4:
      return PeriphType::tim4;
    case TimType::tim5:
      return PeriphType::tim5;
    case TimType::tim6:
      return PeriphType::tim6;
    case TimType::tim7:
      return PeriphType::tim7;
    case TimType::tim8:
      return PeriphType::tim8;
    case TimType::tim9:
      return PeriphType::tim9;
    case TimType::tim10:
      return PeriphType::tim10;
    case TimType::tim11:
      return PeriphType::tim11;
    case TimType::tim12:
      return PeriphType::tim12;
    case TimType::tim13:
      return PeriphType::tim13;
    case TimType::tim14:
      return PeriphType::tim14;
  }
  return std::nullopt;
}

}
}

#endif /* IGB_STM32_BASE_MCU_DEVICE_STM32F446XX_H */
